// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<domain.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAllTasks():Promise<Array<domain.Task>>;

export function GetStats():Promise<Record<string, number>>;

export function SearchTasks(arg1:string):Promise<Array<domain.Task>>;

export function TestMethod():Promise<string>;

export function ToggleTaskCompletion(arg1:number):Promise<domain.Task>;
