// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['app']['App']['DeleteTask'](arg1);
}

export function GetAllTasks() {
  return window['go']['app']['App']['GetAllTasks']();
}

export function GetStats() {
  return window['go']['app']['App']['GetStats']();
}

export function SearchTasks(arg1) {
  return window['go']['app']['App']['SearchTasks'](arg1);
}

export function TestMethod() {
  return window['go']['app']['App']['TestMethod']();
}

export function ToggleTaskCompletion(arg1) {
  return window['go']['app']['App']['ToggleTaskCompletion'](arg1);
}
